# .github/workflows/gh-pages.yml
name: Build and Deploy

on:
  push:
    branches:
      - main  # o "master", según tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/jekyll-build-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-pages-artifact@v1
        with:
          path: './_site'
      - uses: actions/deploy-pages@v2
